{{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cf2cnp.fullname" . }}-auth
  labels:
    {{- include "cf2cnp.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.auth.token | quote }}
{{- end }}
